language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
services:
    - postgresql
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.4-precise
    packages:
      - mongodb-org
before_install:
  - pip install --upgrade pip setuptools
  - pip install mock>=2.0.0
  - pip install -r requirements.test.txt
install:
  - pip install coveralls
  - python setup.py install
script:
  - coverage run setup.py test
after_success:
  - coveralls
